/*******************************************************************************
*
* Header file generated by RDP on Dec 06 2020 18:12:19 from expr.bnf
*
*******************************************************************************/
#ifndef EXPR_H
#define EXPR_H

#include "scan.h"

/* Maximum number of passes */
#define RDP_PASSES 1

/* Time and date stamp */
#define RDP_STAMP "Generated on Dec 06 2020 18:12:19 and compiled on " __DATE__ " at " __TIME__ 

/* Token enumeration */
enum
{
RDP_TT_BOTTOM = SCAN_P_TOP,
RDP_T_16 /* ! */ = SCAN_P_TOP,RDP_T_17 /* != */,RDP_T_18 /* * */,RDP_T_19 /* + */,RDP_T_20 /* - */,RDP_T_21 /* ; */,RDP_T_22 /* < */,RDP_T_23 /* <= */,
RDP_T_24 /* = */,RDP_T_25 /* == */,RDP_T_26 /* > */,RDP_T_27 /* >= */,RDP_T_int,
RDP_TT_TOP
};

/* Tree data type */

typedef struct rdp_tree_data_node
{
  SCAN_DATA
  
} rdp_tree_data;

/* Symbol table support */
typedef struct global_data_node
{
 char* id; integer i; 
} global_data;
extern void * global;
extern global_data * global_temp;
#define global_cast(x) ((global_data *)x)

/* Parser start production */
void TRANSLATION_UNIT(void);

#endif

/* End of expr.h */
