/*******************************************************************************
*
* Parser generated by RDP on Dec 06 2020 17:59:14 from cond.bnf
*
*******************************************************************************/
#include <time.h>
#include "arg.h"
#include "graph.h"
#include "memalloc.h"
#include "scan.h"
#include "set.h"
#include "symbol.h"
#include "textio.h"
#include "cond.h"

char
 *rdp_sourcefilename = NULL,   /* source file name */
 *rdp_outputfilename = "cond.out";         /* output file name */

int
  rdp_symbol_echo = 0,                 /* symbol echo flag */
  rdp_verbose = 0,                     /* verbosity flag */
  rdp_pass;                            /* pass number */

int rdp_error_return = 0;              /* return value for main routine */

char *rdp_tokens = "IGNORE\0" 
"ID\0" "INTEGER\0" "REAL\0" "CHAR\0" "CHAR_ESC\0" "STRING\0" "STRING_ESC\0" "COMMENT\0" 
"COMMENT_VISIBLE\0" "COMMENT_NEST\0" "COMMENT_NEST_VISIBLE\0" "COMMENT_LINE\0" "COMMENT_LINE_VISIBLE\0" "EOF\0" "EOLN\0" "'!'\0" 
"'!='\0" "'+'\0" "'-'\0" "'='\0" "'=='\0" "'if'\0" "'int'\0" "'print'\0" 
"'then'\0" ;

tbl_data * tbl_temp = NULL;
void* tbl = NULL;

/* Load keywords */
static void rdp_load_keywords(void)
{
  scan_load_keyword("!", NULL, RDP_T_16 /* ! */, SCAN_P_IGNORE);
  scan_load_keyword("!=", NULL, RDP_T_17 /* != */, SCAN_P_IGNORE);
  scan_load_keyword("+", NULL, RDP_T_18 /* + */, SCAN_P_IGNORE);
  scan_load_keyword("-", NULL, RDP_T_19 /* - */, SCAN_P_IGNORE);
  scan_load_keyword("=", NULL, RDP_T_20 /* = */, SCAN_P_IGNORE);
  scan_load_keyword("==", NULL, RDP_T_21 /* == */, SCAN_P_IGNORE);
  scan_load_keyword("if", NULL, RDP_T_if, SCAN_P_IGNORE);
  scan_load_keyword("int", NULL, RDP_T_int, SCAN_P_IGNORE);
  scan_load_keyword("print", NULL, RDP_T_print, SCAN_P_IGNORE);
  scan_load_keyword("then", NULL, RDP_T_then, SCAN_P_IGNORE);
}

/* Set declarations */

  set_ BOOL_first = SET_NULL;
  set_ BOOL_stop = SET_NULL;
  set_ DECL_stop = SET_NULL;
  set_ EXPR_first = SET_NULL;
  set_ EXPR_stop = SET_NULL;
  set_ PRIMITIVE_first = SET_NULL;
  set_ PRIMITIVE_stop = SET_NULL;
  set_ S_first = SET_NULL;
  set_ S_stop = SET_NULL;
  set_ STMT_first = SET_NULL;
  set_ STMT_stop = SET_NULL;
  set_ rdp_BOOL_2_first = SET_NULL;
  set_ rdp_BOOL_3_first = SET_NULL;
  set_ rdp_EXPR_2_first = SET_NULL;
  set_ rdp_EXPR_3_first = SET_NULL;
  set_ rdp_S_1_first = SET_NULL;
  set_ rdp_S_2_first = SET_NULL;
  set_ rdp_S_3_first = SET_NULL;

/* Initialise sets */

static void rdp_set_initialise(void)
{
  set_assign_list(&BOOL_first, SCAN_P_ID, SCAN_P_INTEGER, SET_END);
  set_assign_list(&BOOL_stop, SCAN_P_EOF, RDP_T_then,SET_END);
  set_assign_list(&DECL_stop, SCAN_P_ID, SCAN_P_EOF, RDP_T_if, RDP_T_int, RDP_T_print,SET_END);
  set_assign_list(&EXPR_first, SCAN_P_ID, SCAN_P_INTEGER, SET_END);
  set_assign_list(&EXPR_stop, SCAN_P_ID, SCAN_P_EOF, RDP_T_17 /* != */, RDP_T_21 /* == */, RDP_T_if, RDP_T_int, 
RDP_T_print, RDP_T_then,SET_END);
  set_assign_list(&PRIMITIVE_first, SCAN_P_ID, SCAN_P_INTEGER, SET_END);
  set_assign_list(&PRIMITIVE_stop, SCAN_P_ID, SCAN_P_EOF, RDP_T_17 /* != */, RDP_T_18 /* + */, RDP_T_19 /* - */, 
RDP_T_21 /* == */, RDP_T_if, RDP_T_int, RDP_T_print, RDP_T_then,SET_END);
  set_assign_list(&S_first, SCAN_P_ID, RDP_T_if, RDP_T_int, RDP_T_print, SET_END);
  set_assign_list(&S_stop, SCAN_P_EOF,SET_END);
  set_assign_list(&STMT_first, SCAN_P_ID, RDP_T_if, RDP_T_print, SET_END);
  set_assign_list(&STMT_stop, SCAN_P_ID, SCAN_P_EOF, RDP_T_if, RDP_T_int, RDP_T_print,SET_END);
  set_assign_list(&rdp_BOOL_2_first, RDP_T_17 /* != */, RDP_T_21 /* == */, SET_END);
  set_assign_list(&rdp_BOOL_3_first, SCAN_P_ID, SCAN_P_INTEGER, SET_END);
  set_assign_list(&rdp_EXPR_2_first, RDP_T_18 /* + */, RDP_T_19 /* - */, SET_END);
  set_assign_list(&rdp_EXPR_3_first, SCAN_P_ID, SCAN_P_INTEGER, SET_END);
  set_assign_list(&rdp_S_1_first, SCAN_P_ID, RDP_T_if, RDP_T_print, SET_END);
  set_assign_list(&rdp_S_2_first, SCAN_P_ID, RDP_T_if, RDP_T_int, RDP_T_print, SET_END);
  set_assign_list(&rdp_S_3_first, SCAN_P_ID, RDP_T_if, RDP_T_int, RDP_T_print, SET_END);
}

/* Parser forward declarations and macros */
static int BOOL(void);
static void DECL(void);
static int EXPR(void);
static int PRIMITIVE(void);
void S(void);
static void STMT(int flag);

/* Parser functions */
static int BOOL(void)
{
  int result;
  int val;
  {
    result = EXPR();
    if (scan_test_set(NULL, &rdp_BOOL_2_first, NULL))
    { /* Start of rdp_BOOL_2 */
      while (1)
      {
        {
          if (scan_test(NULL, RDP_T_21 /* == */, NULL))
          {
            scan_test(NULL, RDP_T_21 /* == */, &BOOL_stop);
            scan_();
            val = EXPR();
             result = result == val; 
          }
          else
          if (scan_test(NULL, RDP_T_17 /* != */, NULL))
          {
            scan_test(NULL, RDP_T_17 /* != */, &BOOL_stop);
            scan_();
            val = EXPR();
             result = result != val; 
          }
          else
            scan_test_set(NULL, &rdp_BOOL_2_first, &BOOL_stop)          ;
          }
        if (!scan_test_set(NULL, &rdp_BOOL_2_first, NULL)) break;
      }
    } /* end of rdp_BOOL_2 */
    scan_test_set(NULL, &BOOL_stop, &BOOL_stop);
   }
  return result;
}

static void DECL(void)
{
  char* name;
  int val;
  {
    scan_test(NULL, RDP_T_int, &DECL_stop);
    scan_();
    scan_test(NULL, SCAN_P_ID, &DECL_stop);
    name = SCAN_CAST->id;
    scan_();
     if (symbol_lookup_key(tbl, &name, NULL)) \
                 text_message(TEXT_ERROR, "redeclaration of %s\n", name); \
             else \
                 symbol_insert_key(tbl, &name, sizeof(char*), sizeof(tbl_data)); \
          
    if (scan_test(NULL, RDP_T_20 /* = */, NULL))
    { /* Start of rdp_DECL_1 */
      while (1)
      {
        {
          scan_test(NULL, RDP_T_20 /* = */, &DECL_stop);
          scan_();
          val = EXPR();
           tbl_cast(symbol_lookup_key(tbl, &name, NULL))->i = val; 
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_DECL_1 */
    scan_test_set(NULL, &DECL_stop, &DECL_stop);
   }
}

static int EXPR(void)
{
  int result;
  int val;
  {
    result = PRIMITIVE();
    if (scan_test_set(NULL, &rdp_EXPR_2_first, NULL))
    { /* Start of rdp_EXPR_2 */
      while (1)
      {
        {
          if (scan_test(NULL, RDP_T_18 /* + */, NULL))
          {
            scan_test(NULL, RDP_T_18 /* + */, &EXPR_stop);
            scan_();
            val = PRIMITIVE();
             result += val;  
          }
          else
          if (scan_test(NULL, RDP_T_19 /* - */, NULL))
          {
            scan_test(NULL, RDP_T_19 /* - */, &EXPR_stop);
            scan_();
            val = PRIMITIVE();
             result -= val;  
          }
          else
            scan_test_set(NULL, &rdp_EXPR_2_first, &EXPR_stop)          ;
          }
        if (!scan_test_set(NULL, &rdp_EXPR_2_first, NULL)) break;
      }
    } /* end of rdp_EXPR_2 */
    scan_test_set(NULL, &EXPR_stop, &EXPR_stop);
   }
  return result;
}

static int PRIMITIVE(void)
{
  int result;
  char* name;
  {
    if (scan_test(NULL, SCAN_P_INTEGER, NULL))
    {
      scan_test(NULL, SCAN_P_INTEGER, &PRIMITIVE_stop);
      result = SCAN_CAST->data.i;
      scan_();
    }
    else
    if (scan_test(NULL, SCAN_P_ID, NULL))
    {
      scan_test(NULL, SCAN_P_ID, &PRIMITIVE_stop);
      name = SCAN_CAST->id;
      scan_();
       if (!symbol_lookup_key(tbl, &name, NULL)) \
                     text_message(TEXT_ERROR, "%s undeclared\n", name); \
                 else  \
                     result = tbl_cast(symbol_lookup_key(tbl, &name, NULL))->i; \
              
    }
    else
      scan_test_set(NULL, &PRIMITIVE_first, &PRIMITIVE_stop)    ;
    scan_test_set(NULL, &PRIMITIVE_stop, &PRIMITIVE_stop);
   }
  return result;
}

void S(void)
{
  {
    if (scan_test_set(NULL, &rdp_S_2_first, NULL))
    { /* Start of rdp_S_2 */
      while (1)
      {
        {
          if (scan_test(NULL, RDP_T_int, NULL))
          {
            DECL();
          }
          else
          if (scan_test_set(NULL, &rdp_S_1_first, NULL))
          {
            STMT(1);
          }
          else
            scan_test_set(NULL, &rdp_S_2_first, &S_stop)          ;
          }
        if (!scan_test_set(NULL, &rdp_S_2_first, NULL)) break;
      }
    } /* end of rdp_S_2 */
    scan_test_set(NULL, &S_stop, &S_stop);
   }
}

static void STMT(int flag)
{
  char* name;
  int val;
  int cond;
  {
    if (scan_test(NULL, SCAN_P_ID, NULL))
    {
      scan_test(NULL, SCAN_P_ID, &STMT_stop);
      name = SCAN_CAST->id;
      scan_();
      scan_test(NULL, RDP_T_20 /* = */, &STMT_stop);
      scan_();
      val = EXPR();
       if (flag) { \
                          if (!symbol_lookup_key(tbl, &name, NULL)) \
                              text_message(TEXT_ERROR, "%s undeclared\n", name); \
                          else \
                              tbl_cast(symbol_lookup_key(tbl, &name, NULL))->i = val; \
                      } \
                   
    }
    else
    if (scan_test(NULL, RDP_T_if, NULL))
    {
      scan_test(NULL, RDP_T_if, &STMT_stop);
      scan_();
      cond = BOOL();
       cond = cond && flag; 
      scan_test(NULL, RDP_T_then, &STMT_stop);
      scan_();
      STMT(cond);
    }
    else
    if (scan_test(NULL, RDP_T_print, NULL))
    {
      scan_test(NULL, RDP_T_print, &STMT_stop);
      scan_();
      val = EXPR();
       if (flag) { \
                          printf("%i\n", val); \
                      }   \
                   
    }
    else
      scan_test_set(NULL, &STMT_first, &STMT_stop)    ;
    scan_test_set(NULL, &STMT_stop, &STMT_stop);
   }
}

int main(int argc, char *argv[])
{
  clock_t rdp_finish_time, rdp_start_time = clock();
  int
    rdp_symbol_statistics = 0,    /* show symbol_ table statistics flag */
    rdp_line_echo_all = 0,        /* make a listing on all passes flag */
    rdp_filter = 0,               /* filter flag */
    rdp_line_echo = 0;            /* make listing flag */

  unsigned long rdp_textsize = 35000l;   /* size of scanner text array */

  unsigned long rdp_tabwidth = 8l;   /* tab expansion width */

  char* rdp_vcg_filename = NULL;      /* filename for -V option */

  arg_message("rdparser\n" RDP_STAMP "\n\n""Usage: cond [options] source");

  arg_message("");
  arg_boolean('f', "Filter mode (read from stdin and write to stdout)", &rdp_filter);
  arg_boolean('l', "Make a listing", &rdp_line_echo);
  arg_string ('o', "Write output to filename", &rdp_outputfilename);
  arg_boolean('s', "Echo each scanner symbol as it is read", &rdp_symbol_echo);
  arg_boolean('S', "Print summary symbol table statistics", &rdp_symbol_statistics);
  arg_numeric('t', "Tab expansion width (default 8)", &rdp_tabwidth);
  arg_numeric('T', "Text buffer size in bytes for scanner (default 20000)", &rdp_textsize);
  arg_boolean('v', "Set verbose mode", &rdp_verbose);
  arg_string ('V', "Write derivation tree to filename in VCG format", &rdp_vcg_filename);

  rdp_sourcefilename = *arg_process(argc, argv);

  if (rdp_filter)
{
    rdp_sourcefilename = "-";
    rdp_outputfilename = "-";

}
  if (rdp_sourcefilename == NULL)
     arg_help("No source file specified");

  rdp_sourcefilename = text_default_filetype(rdp_sourcefilename, "");
  text_init(rdp_textsize, 25, 100, (int) rdp_tabwidth);
  scan_init(0, 0, 0, rdp_symbol_echo, rdp_tokens);
  tbl = symbol_new_table("tbl", 101, 31, symbol_compare_string, symbol_hash_string, symbol_print_string);
  rdp_set_initialise();
  rdp_load_keywords();
  if (rdp_verbose)
     text_printf("\nrdparser\n" RDP_STAMP "\n\n");
  for (rdp_pass = 1; rdp_pass <= RDP_PASSES; rdp_pass++)
  {
    text_echo(rdp_line_echo_all || (rdp_line_echo && rdp_pass == RDP_PASSES));
    if (text_open(rdp_sourcefilename) == NULL)
      arg_help("unable to open source file");

    text_get_char();
    scan_();

    S();            /* call parser at top level */
    if (text_total_errors() != 0)
      text_message(TEXT_FATAL, "error%s detected in source file\n", text_total_errors() == 1 ? "" : "s");   /* crash quietly */ 
  }
  if (rdp_symbol_statistics)
    symbol_print_all_table_statistics(11);

  text_print_total_errors();
  if (rdp_verbose)
  {
    rdp_finish_time = clock();
    text_message(TEXT_INFO, "%.3f CPU seconds used\n", ((double) (rdp_finish_time-rdp_start_time)) / CLOCKS_PER_SEC);
  }
  return rdp_error_return;
}

/* End of cond.c */
