/*******************************************************************************
*
* Header file generated by RDP on Dec 06 2020 17:59:14 from cond.bnf
*
*******************************************************************************/
#ifndef COND_H
#define COND_H

#include "scan.h"

/* Maximum number of passes */
#define RDP_PASSES 1

/* Time and date stamp */
#define RDP_STAMP "Generated on Dec 06 2020 17:59:14 and compiled on " __DATE__ " at " __TIME__ 

/* Token enumeration */
enum
{
RDP_TT_BOTTOM = SCAN_P_TOP,
RDP_T_16 /* ! */ = SCAN_P_TOP,RDP_T_17 /* != */,RDP_T_18 /* + */,RDP_T_19 /* - */,RDP_T_20 /* = */,RDP_T_21 /* == */,RDP_T_if,RDP_T_int,
RDP_T_print,RDP_T_then,
RDP_TT_TOP
};

/* Tree data type */

typedef struct rdp_tree_data_node
{
  SCAN_DATA
  
} rdp_tree_data;

/* Symbol table support */
typedef struct tbl_data_node
{
 char* id; integer i; 
} tbl_data;
extern void * tbl;
extern tbl_data * tbl_temp;
#define tbl_cast(x) ((tbl_data *)x)

/* Parser start production */
void S(void);

#endif

/* End of cond.h */
