TREE
TRNS_UNIT ::= {EXTN_DECL} .      
EXTN_DECL ::= TYPE_SPEC ID DECL.
TYPE_SPEC ::= 'int' .
DECL      ::= FUNC_DEFN | DECL_LIST .
FUNC_DEFN ::= '(' [PARAMS] ')' CMPD_STMT.
DECL_LIST ::= {',' ID} ';' .
PARAMS    ::= TYPE_SPEC ID {',' TYPE_SPEC ID} .
CMPD_STMT ::= '{' {INTL_DECL | STMT} '}' .
INTL_DECL ::= TYPE_SPEC ID DECL_LIST . 
STMT      ::= TERM_STMT | ITER_STMT .
TERM_STMT ::= (JUMP_STMT | EXPR) ';' .
ITER_STMT ::= 'while' '(' EXPR ')' (CMPD_STMT | STMT) .
JUMP_STMT ::= 'return' EXPR .
EXPR      ::= PRIMARY (ASSIGN | MATH_EXPR) .
ASSIGN    ::= '=' PRIMARY MATH_EXPR .
MATH_EXPR ::= UNARY_OP PRIMARY MATH_EXPR | BOOL_EXPR  .
BOOL_EXPR ::= {BOOL_OP PRIMARY} .
UNARY_OP  ::= '+' | '*' .
BOOL_OP   ::= '==' | '!=' | '>' | '<' | '>=' | '<=' . 
PRIMARY   ::= INTEGER | ID .
