/*******************************************************************************
*
* Header file generated by RDP on Dec 06 2020 18:08:47 from cll1.bnf
*
*******************************************************************************/
#ifndef CLL1_H
#define CLL1_H

#include "scan.h"

/* Maximum number of passes */
#define RDP_PASSES 1

/* Time and date stamp */
#define RDP_STAMP "Generated on Dec 06 2020 18:08:47 and compiled on " __DATE__ " at " __TIME__ 

/* Token enumeration */
enum
{
RDP_TT_BOTTOM = SCAN_P_TOP,
RDP_T_16 /* ! */ = SCAN_P_TOP,RDP_T_17 /* != */,RDP_T_18 /* ( */,RDP_T_19 /* ) */,RDP_T_20 /* * */,RDP_T_21 /* + */,RDP_T_22 /* , */,RDP_T_23 /* ; */,
RDP_T_24 /* < */,RDP_T_25 /* <= */,RDP_T_26 /* = */,RDP_T_27 /* == */,RDP_T_28 /* > */,RDP_T_29 /* >= */,RDP_T_int,RDP_T_return,
RDP_T_while,RDP_T_33 /* { */,RDP_T_34 /* } */,
RDP_TT_TOP
};

/* Tree data type */

typedef struct rdp_tree_data_node
{
  SCAN_DATA
  
} rdp_tree_data;

/* Symbol table support */
/* Parser start production */
void TRNS_UNIT(rdp_tree_data* rdp_tree);

#endif

/* End of cll1.h */
