/*******************************************************************************
*
* Header file generated by RDP on Mar 23 2021 22:19:16 from func.bnf
*
*******************************************************************************/
#ifndef FUNC_H
#define FUNC_H

#include "scan.h"

/* Maximum number of passes */
#define RDP_PASSES 1

/* Time and date stamp */
#define RDP_STAMP "Generated on Mar 23 2021 22:19:16 and compiled on " __DATE__ " at " __TIME__ 

/* Token enumeration */
enum
{
RDP_TT_BOTTOM = SCAN_P_TOP,
RDP_T_16 /* ! */ = SCAN_P_TOP,RDP_T_17 /* != */,RDP_T_18 /* % */,RDP_T_19 /* ( */,RDP_T_20 /* ) */,RDP_T_21 /* * */,RDP_T_22 /* + */,RDP_T_23 /* , */,
RDP_T_24 /* - */,RDP_T_25 /* / */,RDP_T_26 /* ; */,RDP_T_27 /* < */,RDP_T_28 /* <= */,RDP_T_29 /* = */,RDP_T_30 /* == */,RDP_T_31 /* > */,
RDP_T_32 /* >= */,RDP_T_33 /* [ */,RDP_T_34 /* ] */,RDP_T_break,RDP_T_continue,RDP_T_elif,RDP_T_else,RDP_T_if,
RDP_T_int,RDP_T_print,RDP_T_return,RDP_T_while,RDP_T_44 /* { */,RDP_T_45 /* } */,
RDP_TT_TOP
};

/* Tree data type */

typedef struct rdp_tree_data_node
{
  SCAN_DATA
  
} rdp_tree_data;

/* Symbol table support */
typedef struct table_data_node
{
 char* id; int type; int offset; int params; int size; int value; 
} table_data;
extern void * table;
extern table_data * table_temp;
#define table_cast(x) ((table_data *)x)

/* Parser start production */
void TRNS_UNIT(void);

#endif

/* End of rdparser.h */
